# Generated by Django 5.0.3 on 2024-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='StockData',
        ),
    ]
