# Generated by Django 5.0.3 on 2024-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0002_rename_data_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
