# Generated by Django 5.0.3 on 2024-06-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0003_about_ticker_ticker1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=12)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('High', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticker1',
        ),
    ]
