# Generated by Django 5.0.3 on 2024-06-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0004_gathers_delete_ticker1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gathers',
        ),
    ]
