# Generated by Django 5.0.3 on 2024-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0005_delete_gathers'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(max_length=25)),
                ('share_open', models.IntegerField(default=0)),
                ('share_high', models.IntegerField(default=0)),
                ('share_low', models.IntegerField(default=0)),
                ('share_close', models.IntegerField(default=0)),
                ('share_qty', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=5000)),
                ('shares_owned', models.IntegerField(default=0)),
            ],
        ),
    ]
